### PR TITLE
WIP [release-4.9] Use MC kernelArguments field instead of `/etc/pivot/kernel-args` file

### PR DESCRIPTION
**Pull request by vrutkovs**
Rework #247

### CODE REVIEW

**Comment by vrutkovs** [comment]
Still no luck eradicating double reboots - [4.8-okd-nightly -> 4.9 + this PR](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1462825577101660160)

**Comment by vrutkovs** [comment]
Alternative solution: https://github.com/openshift/okd-machine-os/pull/257

**Comment by LorbusChris** [comment]
The e2e install here seems to have the same symptom as reported in https://github.com/openshift/okd/issues/963

**Comment by vrutkovs** [comment]
Closed in favor of #257

**Pull request closed without merging**
