### PR TITLE
[release-4.11] overlay: add selinux update script from 05rhcos

### PR DESCRIPTION
**Pull request by vrutkovs**
This should apply RHCOS changes, selinux policy upgrade in particular

Ref: https://github.com/okd-project/okd/issues/1317

### CODE REVIEW

**Comment by LorbusChris** [comment]
This pulls in a lot. Are we sure everything in that overlay is compatible?

**Comment by vrutkovs** [comment]
>Are we sure everything in that overlay is compatible?

Hmm, you're right, lets pull in just the necessary bits in 4.11 - and work with RHCOS folks to make it compatible / split it for 4.12?

/hold

**Comment by vrutkovs** [comment]
alert/etcdGRPCRequestsSlow
/override ci/prow/e2e-aws

**Comment by vrutkovs** [comment]
/hold cancel

Ready for review, added just the selinux update bit

**Comment by LorbusChris** [comment]
@vrutkovs what's the reason for NM-plugins overlay change? It looks like it's empty now (or rather, only contains the statoverride file and dropping https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/14NetworkManager-plugins/usr/lib/NetworkManager/conf.d/10-disable-default-plugins.conf). Was that your intention?

Related: I've filed https://github.com/coreos/fedora-coreos-config/pull/1991 to clean up the config in FCOS

**Comment by vrutkovs** [comment]
Not sure why, but the config file already exists, see [this run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_okd-machine-os/451/pull-ci-openshift-okd-machine-os-release-4.11-images/1574646397783773184#1:build-log.txt%3A1318)

**Comment by LorbusChris** [comment]
huh that is unexpected. Is the error reproducible?

**Comment by LorbusChris** [comment]
Ah, there's a dupe of that in 05rhcos: https://github.com/openshift/os/blob/master/overlay.d/05rhcos/usr/lib/NetworkManager/conf.d/10-disable-default-plugins.conf
Of you only pull in the selinux part here, this shouldn't occur.

**Comment by vrutkovs** [comment]
>Ah, there's a dupe of that in 05rhcos: [openshift/os@master/overlay.d/05rhcos/usr/lib/NetworkManager/conf.d/10-disable-default-plugins.conf](https://github.com/openshift/os/blob/master/overlay.d/05rhcos/usr/lib/NetworkManager/conf.d/10-disable-default-plugins.conf)
Of you only pull in the selinux part here, this shouldn't occur.


Oh, right, that's probably unnecessary after pulling just the selinux bit

**Pull request merged**
