### PR TITLE
Update a list of vendored RPMs

### PR DESCRIPTION
**Pull request by vrutkovs**
Built using the following procedure:

* Boot into FCOS next
* Run 
```
rpm-ostree update \
       --install glusterfs \
       --install glusterfs-fuse \
       --install open-vm-tools \
       --install NetworkManager-ovs \
       --install usbguard
       --install kernel-devel
```
  rpm-ostree would output a list of added dependencies RPMs required to
  install these RPMs

### CODE REVIEW

**Comment by LorbusChris** [comment]
we really have to get rid of python (https://bugzilla.redhat.com/show_bug.cgi?id=1901144) and perl (possibly solved with https://github.com/coreos/fedora-coreos-config/pull/756) here.

**Comment by LorbusChris** [comment]
hm wrt perl, I don't think any of those packages actually require the perl deps:
```
$ dnf repoquery --requires --resolve glusterfs glusterfs-fuse usbguard open-vm-tools NetworkManager-ovs kernel-devel
Last metadata expiration check: 0:04:34 ago on Fri 04 Dec 2020 12:31:26 CET.
NetworkManager-1:1.26.4-1.fc33.x86_64
attr-0:2.4.48-10.fc33.x86_64
audit-libs-0:3.0-0.21.20191104git1c2f876.fc33.i686
audit-libs-0:3.0-0.21.20191104git1c2f876.fc33.x86_64
bash-0:5.0.17-2.fc33.x86_64
coreutils-0:8.32-12.fc33.x86_64
coreutils-single-0:8.32-12.fc33.x86_64
findutils-1:4.7.0-7.fc33.x86_64
fuse-0:2.9.9-10.fc33.x86_64
fuse-libs-0:2.9.9-10.fc33.i686
fuse-libs-0:2.9.9-10.fc33.x86_64
glib2-0:2.66.3-1.fc33.i686
glib2-0:2.66.3-1.fc33.x86_64
glibc-0:2.32-2.fc33.i686
glibc-0:2.32-2.fc33.x86_64
glusterfs-0:8.2-1.fc33.x86_64
glusterfs-client-xlators-0:8.2-1.fc33.i686
glusterfs-client-xlators-0:8.2-1.fc33.x86_64
grep-0:3.4-5.fc33.x86_64
iproute-0:5.8.0-1.fc33.x86_64
jansson-0:2.13.1-1.fc33.x86_64
libdrm-0:2.4.102-2.fc33.i686
libdrm-0:2.4.102-2.fc33.x86_64
libgcc-0:10.2.1-9.fc33.i686
libgcc-0:10.2.1-9.fc33.x86_64
libgcrypt-0:1.8.7-1.fc33.i686
libgcrypt-0:1.8.7-1.fc33.x86_64
libgfrpc0-0:8.2-1.fc33.x86_64
libgfxdr0-0:8.2-1.fc33.x86_64
libglusterfs0-0:8.2-1.fc33.x86_64
libgpg-error-0:1.37-2.fc33.i686
libgpg-error-0:1.37-2.fc33.x86_64
libmspack-0:0.10.1-0.4.alpha.fc33.i686
libmspack-0:0.10.1-0.4.alpha.fc33.x86_64
libqb-0:2.0.1-2.fc33.i686
libqb-0:2.0.1-2.fc33.x86_64
libstdc++-0:10.2.1-9.fc33.i686
libstdc++-0:10.2.1-9.fc33.x86_64
libtirpc-0:1.2.6-2.rc4.fc33.i686
libtirpc-0:1.2.6-2.rc4.fc33.x86_64
libuuid-0:2.36-3.fc33.x86_64
libxml2-0:2.9.10-8.fc33.i686
libxml2-0:2.9.10-8.fc33.x86_64
mdatp-0:100.90.70-1.x86_64
openssl-libs-1:1.1.1h-1.fc33.i686
openssl-libs-1:1.1.1h-1.fc33.x86_64
openvswitch-0:2.14.0-2.fc33.i686
openvswitch-0:2.14.0-2.fc33.x86_64
pciutils-0:3.6.4-2.fc33.x86_64
perl-interpreter-4:5.32.0-464.fc33.x86_64
protobuf-0:3.12.4-1.fc33.i686
protobuf-0:3.12.4-1.fc33.x86_64
psmisc-0:23.3-4.fc33.x86_64
sed-0:4.8-5.fc33.x86_64
shadow-utils-2:4.8.1-5.fc33.x86_64
systemd-0:246.6-3.fc33.i686
systemd-0:246.6-3.fc33.x86_64
systemd-libs-0:246.6-3.fc33.i686
systemd-libs-0:246.6-3.fc33.x86_64
tar-2:1.32-6.fc33.x86_64
util-linux-0:2.36-3.fc33.i686
util-linux-0:2.36-3.fc33.x86_64
which-0:2.21-20.fc33.x86_64
xmlsec1-0:1.2.29-2.fc33.i686
xmlsec1-0:1.2.29-2.fc33.x86_64
xmlsec1-openssl-0:1.2.29-2.fc33.i686
xmlsec1-openssl-0:1.2.29-2.fc33.x86_64
zlib-0:1.2.11-23.fc33.x86_6
```

**Comment by vrutkovs** [comment]
>I guess we'll just have to live with it.

Right, not much we can do about it. Luckily these RPMs are optional and don't make machine-os-content size explode

**Pull request merged**
