### PR TITLE
WIP Revert "Undo systemd-resolved change in https://github.com/systemd/sy…

### PR DESCRIPTION
**Pull request by vrutkovs**
…stemd/pull/17201"

This reverts commit 2fde9e6d5d6a75b976f6b53936168009d755c071.

This change seems to break vSphere CI environment

### CODE REVIEW

**Comment by fortinj66** [comment]
I'm curious how this is breaking CI...

**Comment by vrutkovs** [comment]
Instead of `ip-foo-bar.us-west-1.internal` nodes get local `ci-foo-bar-worker-0-baz` names, create CSR for that name - and node approver won't let them join the cluster.

This PR won't go in as is, its used to diagnose the problem.

Also lets see if that affects oVirt:
/test e2e-ovirt

**Comment by fortinj66** [comment]
That's really odd as that change shouldn't affect hostname assignment...

**Comment by vrutkovs** [comment]
Alternatively https://github.com/openshift/okd-machine-os/pull/165 could help

**Comment by vrutkovs** [comment]
No longer needed - reverted MCO commits which prevented from setting hostname from VM details

**Pull request closed without merging**
