### PR TITLE
Pin Fedora kernel

### PR DESCRIPTION
**Pull request by LorbusChris**
/cc @fortinj66

### CODE REVIEW

**Comment by fortinj66** [comment]
The errors in `e2e-vsphere` seem to happen all the time trying to download wildfly images...

**Comment by jcpowermac** [comment]
> The errors in `e2e-vsphere` seem to happen all the time trying to download wildfly images...

If they are from docker.io then certainly possible we are over our quota. VMC and IBM are all NAT'ed so have a single egress.

**Comment by fortinj66** [comment]
e2e-aws-upgrade failures are almost all disruption tests...  These also seem to fail very often

**Comment by vrutkovs** [comment]
/override ci/prow/e2e-aws-upgrade

Disruption issues

**Pull request merged**
