### PR TITLE
WIP Unpin selinux-policy

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by Elbehery** [comment]
v

**Comment by Elbehery** [comment]
> ci/prow/e2e-aws [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_okd-machine-os/178/pull-ci-openshift-okd-machine-os-master-e2e-aws/1425108621045272576)	`/test e2e-aws`

@vrutkovs exactly the two test cases failed as per BZ.

**Comment by vrutkovs** [comment]
/retest

Rebuilding so that it could be mirrored to quay

**Comment by vrutkovs** [comment]
Closed in favor of https://github.com/openshift/okd-machine-os/pull/183

**Pull request closed without merging**
