### PR TITLE
Use `ex rebuild` to pull from COPR

### PR DESCRIPTION
**Pull request by cgwalters**
This works around https://github.com/coreos/rpm-ostree/issues/4037

### CODE REVIEW

**Comment by cgwalters** [comment]
OK I rebased :surfer: this on master

**Comment by cgwalters** [comment]
I think upgrades will be broken until this merges
/override e2e-gcp-upgrade

**Comment by LorbusChris** [comment]
What's the reason for removing `ostree container commit`. Is it not needed?

**Comment by cgwalters** [comment]
> What's the reason for removing ostree container commit. Is it not needed?

It's a bug, introduced by https://github.com/ostreedev/ostree-rs-ext/pull/367 and fixed by https://github.com/ostreedev/ostree-rs-ext/pull/377 and waiting on someone to review https://github.com/ostreedev/ostree-rs-ext/pull/379 so I can bump rpm-ostree, which will get the fixed version into the COPR.

**Pull request merged**
