### PR TITLE
OKD-63: Use CoreOS Continuous copr packages

### PR DESCRIPTION
**Pull request by vrutkovs**
Fresh `rpm-ostree` from this COPR should fix https://issues.redhat.com/browse/OKD-63

### CODE REVIEW

**Comment by vrutkovs** [comment]
/override ci/prow/e2e-aws-ovn

known issue
/retest

**Comment by vrutkovs** [comment]
/override ci/prow/e2e-aws-ovn
/override ci/prow/e2e-gcp-upgrade

known issue
/lgtm

**Comment by cgwalters** [comment]
Hmmm for some strange reason this seems to be pulling in a much older package; we're getting `rpm-ostree-2022.13.36.gdbae1fe4-1` when the latest is `rpm-ostree-libs-2022.13.91.ga6fcdf60-1`.

Looking into this...

**Pull request merged**
