### PR TITLE
Add qemu-guest-agent RPM to extensions

### PR DESCRIPTION
**Pull request by LorbusChris**
The RPM has been added to RHCOS [1].

[1] https://github.com/openshift/os/pull/451

### CODE REVIEW

**Comment by vrutkovs** [comment]
Installer needs to list it in okdextensions.go as well, working on it

**Comment by vrutkovs** [comment]
This needs an installer change to include this RPM in a list of installed extensions.

https://github.com/openshift/okd-machine-os/pull/19 should have unified that, so I'll update 4.7 installer fork to re-use these files. Once it has landed this PR needs to update os extension manifests and pass the bootstrap.

**Comment by LorbusChris** [comment]
@vrutkovs rebased, PTAL

**Pull request merged**
