### PR TITLE
Fix GCP hostname and DNS resolution

### PR DESCRIPTION
**Pull request by vrutkovs**
Cherry-pick of release-4.6 PRs to master:
* Layer files on host instead of creating them in the script
* Run Afterburn on GCP 
* Configure systemd-resolved

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

Waiting for 4.7 nightly w/ NFS test skipped to be promoted

**Comment by vrutkovs** [comment]
4.7 fails with `bootkube.sh[7175]: unknown flag: --etcd-discovery-domain` - needs 4.7-specific installer rebase

**Comment by LorbusChris** [comment]
@vrutkovs please link https://github.com/openshift/machine-config-operator/pull/2217 and https://github.com/openshift/okd/issues/380 in the respective commits for posterity :)

**Comment by vrutkovs** [comment]
Done, reworked commits

**Comment by vrutkovs** [comment]
/retest

HTTP 500 from quay :/

**Comment by LorbusChris** [comment]
couldn't pull images from quay due to an outage - should be resolved now
/retest

**Comment by vrutkovs** [comment]
Not sure why openshift-apiserver can't rollout: a lot of
>controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"

in the logs. Apparently we're hitting https://bugzilla.redhat.com/show_bug.cgi?id=1874385

**Comment by LorbusChris** [comment]
cluster never came up with `Cluster operator authentication Degraded is True`
/retest

**Comment by vrutkovs** [comment]
Ingress operator stuck in ContainerCreating w/ `failed to fetch token: the API server does not have TokenRequest endpoints enabled` error

**Comment by vrutkovs** [comment]
Oh, I forgot to add a commit which sets correct Ignition version in 4.7 fork of installer (https://github.com/vrutkovs/installer/commits/fcos-4.7)

Fixed now.

**Comment by vrutkovs** [comment]
/hold cancel

Cluster started and passed tests, woot!

**Pull request merged**
