### PR TITLE
Remove cliwrap install-to-root: this seems to break rpm SELinux labels

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by andfasano** [comment]
> @vrutkovs: cannot checkout release-4.15: error checking out "release-4.15": exit status 1 error: pathspec 'release-4.15' did not match any file(s) known to git

doh?

/cherry-pick release-4.15

**Comment by andfasano** [comment]
Looks like it was already included? https://github.com/openshift/okd-machine-os/commit/4fcfb96c4e3b6299772fac265de68dd1ae841993

**Comment by vrutkovs** [comment]
Yeah, I branched release-4.15 from master just now, now waiting for it to build and land

**Comment by andfasano** [comment]
aahh :)

**Pull request merged**
