### PR TITLE
WIP entrypoint.sh: use rawhide stream

### PR DESCRIPTION
**Pull request by vrutkovs**
This would help us estimate changes in Fedora 34

### CODE REVIEW

**Comment by LorbusChris** [comment]
vsphere seems to be missing a binary
```
/bin/bash: line 39: govc: command not found
```

**Comment by vrutkovs** [comment]
I tested the payload generated by CI and seems to be missing `pod` image:
```
[root@vrutkovs-hkf47-bootstrap core]# sh -x /usr/local/bin/crio-configure.sh
+ set -euo pipefail
+ . /usr/local/bin/release-image.sh
+++ podman inspect registry.build02.ci.openshift.org/ci-op-lqfmv5ys/release:latest --format '{{ index .RepoDigests 0 }}'
++ RELEASE_IMAGE_DIGEST=registry.build02.ci.openshift.org/ci-op-lqfmv5ys/release@sha256:3fad953b1cdb79b5cfd3069a213968e489b9c85a5b51fcb162947bc2a0d2dd9c
++ [[ -z registry.build02.ci.openshift.org/ci-op-lqfmv5ys/release@sha256:3fad953b1cdb79b5cfd3069a213968e489b9c85a5b51fcb162947bc2a0d2dd9c ]]
++ image_for pod
++ podman run --quiet --rm --net=none registry.build02.ci.openshift.org/ci-op-lqfmv5ys/release@sha256:3fad953b1cdb79b5cfd3069a213968e489b9c85a5b51fcb162947bc2a0d2dd9c image pod
F0309 14:35:45.842246       1 image.go:32] error: error: Unknown name requested, could not find pod in UpdatePayload
```
Can't think of a reason why CI won't include that in the payload

**Pull request closed without merging**
