### PR TITLE
[release-4.10] Update submodules

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by fortinj66** [comment]
I'm curious why you deleted those two services...  The resolv.conf one fixes the issue when systemd-resolved puts just a '.' in search (which breaks name resolution) and the 2nd (hopefully) fixes the rampant CoreDNS CPU and I/O issues...

**Comment by LorbusChris** [comment]
I'm doing some testing over in https://github.com/openshift/okd-machine-os/pull/328

We're possibly hitting https://bugzilla.redhat.com/show_bug.cgi?id=2058030

**Comment by LorbusChris** [comment]
@fortinj66 this is still a WIP. The fix that is currently in palce is an ugly hack and I'm trying to replace it with a proper solution here (i.e. replacing /etc/resolv.conf with a symlink to `/run/NetworkManager/resolv.conf`, which should tell systemd-resolved to let NM manage that file.

However, overwriting the symlink that already exists with the new one isn't currently supported by the build env in this repo (it will be possible in the future though when moving to CoreOS Layering, see https://github.com/openshift/okd-machine-os/pull/299 and https://github.com/coreos/fedora-coreos-config/pull/1622)

**Comment by fortinj66** [comment]
The problem is that NM and systemd-resolved are still not playing together well. Since systemd-resolved is managing DNS, NM should be using systemd-resolved config, not its own. 

If you point /etc/resolv.conf as you indicate all sorts of things will break.

**Comment by LorbusChris** [comment]
I'll drop this commit for now. A switch for this setting should probably be exposed in the config, i.e. making this behaviour configurable: https://github.com/systemd/systemd/pull/17201

**Comment by fortinj66** [comment]
Good luck with that rabbit hole:

https://bugzilla.redhat.com/show_bug.cgi?id=1976858
https://bugzilla.redhat.com/show_bug.cgi?id=1874419

**Comment by LorbusChris** [comment]
https://github.com/systemd/systemd/pull/22868

**Comment by fortinj66** [comment]
@LorbusChris as far as I know the only case we have issues with `search .` is when nodes are being provisioned with UPI and kernel arguments with static IPs as there is no kernel argument to pass a DNS search parameter.  (Although I suppose if DHCP didn't have it configured it could be an issue also.)  

This isn't an OpenShift issue, it's a Fedora/FCOS issue and can be reproduced outside of OpenShift pretty easily.

**Comment by fortinj66** [comment]
Also, since the `fix-resolv-conf-search.service` really has two very different and unrelated fixes, it should probably be broken up so that the 
`ExecStart=/usr/bin/cp /run/systemd/resolve/resolv.conf /var/run/NetworkManager/resolv.conf` is moved to a different service.

**Comment by LorbusChris** [comment]
Thanks @fortinj66, I'll copy your comment over to https://github.com/systemd/systemd/pull/22868 to make this context visible there as well.

Could you provide me with some more info on the second issue here, i.e. why `cp /run/systemd/resolve/resolv.conf /var/run/NetworkManager/resolv.conf` is needed?

**Comment by fortinj66** [comment]
I'm not sure exactly why Vadim put it there initially but what I found during my research into the high CPU issue for coreDNS is that the coredns monitor which runs with coredns uses `/var/run/NetworkManager/resolv.conf` to configure coreDNS.  Since NM and systemd-resolved still don't work well together, this breaks coreDNS as NM still expects 127.0,0,53 to be the default DNS provider.  Copying the systemd-resolved version in /etc/resolv.conf "fixes/hacks" the issue.  

The best solution would be to have better integration between systemd and NM
An OK solution would be to have coredns monitor use /etc/resolv.conf as this "should" always be correct.

Here is a link to one discussion of the issue.

https://github.com/openshift/okd/issues/978#issuecomment-1073349737

**Comment by LorbusChris** [comment]
Looks like https://github.com/openshift/machine-config-operator/pull/3041 might be able to solve this second issue?

**Comment by fortinj66** [comment]
I found the issue:

```
Apr 01 20:53:03 localhost.localdomain systemd[1]: Starting Open vSwitch Database Unit...
Apr 01 20:53:04 localhost.localdomain ovs-ctl[2270]: ovsdb-tool: I/O error: /etc/openvswitch/conf.db: open failed (Permission denied)
Apr 01 20:53:04 localhost.localdomain ovs-ctl[2272]: ovsdb-server: I/O error: /etc/openvswitch/conf.db: failed to lock lockfile (Resource temporarily unavailable)
Apr 01 20:53:04 localhost.localdomain ovs-ctl[2227]: Starting ovsdb-server ... failed!
```

During the upgrade the file ownership in /etc/openvswitch is changed to the following:

```
[core@localhost openvswitch]$ ls -al
total 624
drwxr-xr-x.  2 gluster gluster     86 Apr  1 21:16 .
drwxr-xr-x. 90 root    root      8192 Apr  1 21:22 ..
-rw-------.  1 gluster gluster      0 Apr  1 18:[  606.270257] audit: type=1334 audit(1648848415.242:254): prog-id=0 op=UNLOAD
36 .conf.db.~lock~
-rw-r-----.  1 gluster gluster 618081 Apr  1 21:16 conf.db
-rw-r--r--.  1 gluster gluster    163 Apr  1 18:35 default.conf
-rw-r--r--.  1 gluster gluster [  606.329193] audit: type=1334 audit(1648848415.242:255): prog-id=0 op=UNLOAD
    37 Apr  1 18:36 system-id.conf
[core@localhost openvswitch]$ ls -aln
total 624
drwxr-xr-x.  2 983 979     86 Apr  1 21:16 .
drwxr-xr-x. 90   0   0   8192 Apr  1 21:22 ..
-rw-------.  1 983 979      0 Apr  1 18:36 .conf.db.~lock~
-rw-r-----.  1 983 979 618081 Apr  1 21:16 conf.db
-rw-r--r--.  1 983 979    163 Apr  1 18:35 default.conf
-rw-r--r--.  1 983 979     37 Apr  1 18:36 system-id.conf
```

it should be:

```

[core@localhost openvswitch]$ ls -al
total 624
drwxr-xr-x.  2 openvswitch gluster     86 Apr  1 21:16 .
drwxr-xr-x. 90 root        root      8192 Apr  1 21:22 ..
-rw-------.  1 openvswitch gluster      0 Apr  1 18:36 .conf.db.~lock~
-rw-r-----.  1 openvswitch gluster 618081 Apr  1 21:16 conf.db
-rw-r--r--.  1 openvswitch gluster    163 Apr  1 18:35 default.conf
-rw-r--r--.  1 openvswitch gluster     37 Apr  1 18:36 system-id.conf
[core@localhost openvswitch]$ 
[core@localhost openvswitch]$ ls -aln
total 624
drwxr-xr-x.  2 985 979     86 Apr  1 21:16 .
drwxr-xr-x. 90   0   0   8192 Apr  1 21:22 ..
-rw-------.  1 985 979      0 Apr  1 18:36 .conf.db.~lock~
-rw-r-----.  1 985 979 618081 Apr  1 21:16 conf.db
-rw-r--r--.  1 985 979    163 Apr  1 18:35 default.conf
-rw-r--r--.  1 985 979     37 Apr  1 18:36 system-id.conf
```

Changing the file ownership and rebooting resolves the issue.

So the question is where is this being changed???

**Comment by vrutkovs** [comment]
MCO is doing that - https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/units/ovs-vswitchd.service.yaml

**Comment by vrutkovs** [comment]
Re-introduced that MCO PR as a dropin in okd-machine-os  - https://github.com/openshift/okd-machine-os/pull/331 - lets see if that works

**Comment by LorbusChris** [comment]
Thanks for investigating this @fortinj66, and also @vrutkovs for working on it.
https://github.com/openshift/machine-config-operator/pull/2423 can't be re-opened. Would you mind re-creating it? Or let me know  and I'll do it. I'd prefer this fix to live in MCO proper in the longer term.

**Comment by LorbusChris** [comment]
I've reopened https://bugzilla.redhat.com/show_bug.cgi?id=1931507

**Comment by LorbusChris** [comment]
Upgrade blockers have been resolved. Submodules will be updated separately.

**Pull request closed without merging**
