### PR TITLE
Update to cri-o 1.23

### PR DESCRIPTION
**Pull request by LorbusChris**
Consume cri-o from Go 1.17 COPR builds.
The latest version of cri-tools is still 1.22 as of this writing

### CODE REVIEW

**Comment by LorbusChris** [comment]
cc @haircommander

**Comment by vrutkovs** [comment]
We can build official CRI-O builds at build.opensuse.org instead of custom COPR repo?

**Comment by LorbusChris** [comment]
> We can build official CRI-O builds at build.opensuse.org instead of custom COPR repo?

I'm not aware that the builds from https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.23 are official in any way - to me they look like another downstream builds (for Kubic, not Fedora). Cc'ing @haircommander for clarification for what those builds are exactly. As such builds, they also don't follow the Fedora RPM spec guidelines.

Since Go 1.17 isn't available in Fedora yet, and won't be until F36 arrives, there are no builds for it from the Kubic repo on OBS either, so we'll need a stop-gap solution anyway. The RPMs in this COPR are built off of the official Fedora RPM specs.

**Comment by LorbusChris** [comment]
With cri-o 1.23 in, we'll also finally be able to try and drop the MCO fork.

**Comment by haircommander** [comment]
> I'm not aware that the builds from https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.23 are official in any way - to me they look like another downstream builds (for Kubic, not Fedora). 

they are official, I package them in addition to the fedora native packages :) 

> As such builds, they also don't follow the Fedora RPM spec guidelines.

what guidlines? it's the same spec file

**Comment by LorbusChris** [comment]
Sorry, I think I confused the cri-o specfile with the one from the Golang package on OBS which doesn't follow the Fedora Packaging Guidelines, thanks for clarifying!

I tried to build golang 1.17 and cri-o 1.23 on OBS but to no avail, so I did the COPR builds as that's a system I'm familiar with.

Since Golang 1.17 won't land in Fedora 35, there won't be an official cri-o 1.23 build for F35 either.
@vrutkovs @haircommander how should be proceed?

**Comment by vrutkovs** [comment]
OBS builds its own golang package. I'm not too concerned that its not using official Fedora golang as long as we use a supported CRI-O package

**Comment by haircommander** [comment]
technically, I am the one building the golang package in OBS at the moment, as none of the distributions have the required golang anymore. it's a rebuild of https://build.opensuse.org/package/show/home:alvistack/golang-go-1.17.5 at the time of writing

at this point "supported" is a matter of "does @haircommander have time to help if something needs updating", which I'm happy to try to allocate for OKD :)

**Comment by LorbusChris** [comment]
closing in favor of #276

**Pull request closed without merging**
