### PR TITLE
overlay: update selinux update script from 05rhcos

### PR DESCRIPTION
**Pull request by MattPOlson**
remove version check from script so that it will run in fcos

### CODE REVIEW

**Comment by vrutkovs** [comment]
/ok-to-test
/approve
/lgtm
/cherrypick release-4.13

Thank you!

**Comment by vrutkovs** [comment]
```
Apr 18 18:57:26.064527 localhost systemd[1]: Starting rhcos-selinux-policy-upgrade.service - RHEL CoreOS Rebuild SELinux Policy If Necessary...
Apr 18 18:57:26.067994 localhost rhcos-rebuild-selinux-policy[884]: RHEL_VERSION=Assuming we have new enough ostree
```
that doesn't seem to have worked :/

**Comment by vrutkovs** [comment]
It now runs - but fails:
```
Apr 19 09:25:10.267311 localhost rhcos-rebuild-selinux-policy[842]: ls: cannot access '/usr/etc/selinux/targeted/policy/policy.31': No such file or directory
Apr 19 09:25:10.267311 localhost rhcos-rebuild-selinux-policy[842]: ls: cannot access '/etc/selinux/targeted/policy/policy.31': No such file or directory
```

**Comment by MattPOlson** [comment]
Would this work to account for different policy version numbers in different releases.

`ls -al /{usr/,}etc/selinux/targeted/policy/policy.*`
`if ! cmp --quiet /{usr/,}etc/selinux/targeted/policy/policy.*; then`

**Comment by vrutkovs** [comment]
I don't like the idea off using wildcards tbh, especially in a non-critical path where its easy to miss this failure. Lets use hardcoded `.33` for now and update this later when we'll make sure this reliably works?

**Comment by MattPOlson** [comment]
Yea that sounds good to me.

**Comment by MattPOlson** [comment]
Looks good, thanks!

**Pull request merged**
