### PR TITLE
manifest: Use cri-o module from Fedora

### PR DESCRIPTION
**Pull request by LorbusChris**
/cc @vrutkovs 
/cc @haircommander 
/cc @jlebon

### CODE REVIEW

**Comment by LorbusChris** [comment]
It looks like cri-o is still at version 1.19 in both f34 and f35 modular repos. This can probably wait until we've rebased to f35, but it'd be great if we could start consuming cri-o from Fedora modular repos after that.

**Comment by vrutkovs** [comment]
We're already using upstream repos for crio, what's the benefit of waiting more time for it to be packaged as a module?

**Comment by jlebon** [comment]
> We're already using upstream repos for crio, what's the benefit of waiting more time for it to be packaged as a module?

Indeed, that's up to OKD to decide. I can say at least that doing so aligns better with https://github.com/coreos/fedora-coreos-tracker/issues/767. I think we should add CI coverage for the Fedora modules in FCOS and if OKD uses the modules too, then CI could test it by simply running OKD node tests too, which I think increase the value a lot. Of course, this is all also related to https://github.com/openshift/okd-machine-os/issues/210.

**Comment by LorbusChris** [comment]
Build failure due to https://status.quay.io/incidents/rm3k6b5nby8m

**Comment by haircommander** [comment]
I am not sure why it takes so long, but I've finally seen 1.22 builds in bodhi:  https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2021-faf9184bbd once that makes it through, I *think* this will work?

**Comment by LorbusChris** [comment]
Ah yeah, thanks I forgot we're still on F34 :man_facepalming:

While you're at this, any plans to do 1.23 builds soon? :innocent:

**Comment by haircommander** [comment]
I am actively trying to get the module build to work! since it requires go 1.17 there may be a delay while fedora get it. [the dist-git](https://src.fedoraproject.org/rpms/golang) seems to indicate it's on 1.16 but I saw an [article](https://www.phoronix.com/scan.php?page=news_item&px=Fedora-35-Golang-1.17-LLVM-13) saying it'll make f35 so idk)

**Comment by LorbusChris** [comment]
It looks like Go 1.17 has unfortunately been deferred to F36 :(
https://pagure.io/fedora-docs/release-notes/issue/713#comment-748924

**Comment by LorbusChris** [comment]
OK, the module seems to be available now, but there's a new problem:
```
error: Problems appeared for module enable request:
  - Modular dependency problem: Problem: conflicting requests
  - nothing provides module(platform:f34) needed by module cri-o:1.22:3420211203192929:058368ca.x86_64
```
@jlebon any idea?

**Comment by jlebon** [comment]
> OK, the module seems to be available now, but there's a new problem:
> 
> ```
> error: Problems appeared for module enable request:
>   - Modular dependency problem: Problem: conflicting requests
>   - nothing provides module(platform:f34) needed by module cri-o:1.22:3420211203192929:058368ca.x86_64
> ```
> 
> @jlebon any idea?

Hmm not sure offhand, I'd have to dig in and try to reproduce it on the roughly equivalent FCOS 34 version. Usually, this works by libdnf looking at the `base-module` `Provides`, which [is clearly present in f34](https://src.fedoraproject.org/rpms/fedora-release/blob/031458279878f649c40170b8cc87596624ea44ec/f/fedora-release.spec#_88).

**Comment by LorbusChris** [comment]
we'll have to wait with this until there's a cri-o 1.23(++) module available, which won't be the case before F36
/hold

**Comment by vrutkovs** [comment]
I'm a bit concerned about fixes taking more time to land in Fedora (due to Bodhi), but I think we'll take it.

However lets move "bump to F36" in a separate PR as its quite a big change

**Comment by LorbusChris** [comment]
/retitle manifest: Use cri-o module from Fedora
/hold

**Pull request merged**
